<?php


namespace frontend\controllers;


use yii\web\Controller;

class AboutUsController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index', []); // TODO: Change the autogenerated stub
    }
}