<?php


namespace frontend\controllers;


use frontend\models\NewsModels;
use yii\base\Model;
use yii\web\Controller;

class BlogController extends Controller
{

    public function actionIndex()
    {
        $ModelNews = new NewsModels();
        $data = $ModelNews->getOneNewsRecord();
        return $this->render('index', [
            'data' => $data
        ]); // TODO: Change the autogenerated stub
    }
}