<?php


namespace frontend\controllers;


use yii\web\Controller;
use yii\web\Session;
use Yii;

class CheckoutController extends Controller
{
    public function actionIndex()
    {
        $session = Yii::$app->session;
        $inforCart = $session['cart'];
        return $this->render('index',[
            'inforCart'=>$inforCart
        ]);
    }

    public function actionSaleproduct()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

}