<?php


namespace frontend\widgets;


use yii\base\Widget;

class FooterWidget extends \yii\base\Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        return $this->render('footerWidgets', []);
    }
}