<?php
namespace frontend\widgets;
use frontend\models\CategoryModels;
use frontend\common\Cart;
use Yii;
use yii\web\Session;

class HeaderWidget extends \yii\base\Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        $session = Yii::$app->session;
        $inforCart = $session['cart'];

        $modelCategory = new CategoryModels();
        $data = $modelCategory->getOneCategoryRecord();
        return $this->render('headerWidgets', [
            'data'=>$data,
            'inforCart'=>$inforCart
        ]);
    }

}